### ISSUE TITLE
for help...I want to analyze he network in the models/default/models.h5

### ISSUE THREAD

**Issue by minghust** [bnegreve/rasta#1]
hi, I'm a student major in CS, and I show interest in deep learning, I think your repo is very fantastic! I want to know how the network works in the models/default/models.h5(the decaf6 in your code don't work...), so could you tell me what should I do to get the default models source code to analyze it, thank a lot.

**Comment by bnegreve** [comment]
Sorry, for the late reply.

Models files are weights for the neural networks (not code). You cannot "analyze" them directly to understand how the network works. Instead you have to understand how it is trained.

**Comment by minghust** [comment]
Oh, I see, Thanks for your reply~
